# Generated by Django 4.2.3 on 2023-12-10 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Client name")),
                ("description", models.TextField(verbose_name="Client say")),
                ("image", models.ImageField(default="default.png", upload_to="client")),
            ],
        ),
        migrations.CreateModel(
            name="RecentWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Work title")),
                ("image", models.ImageField(upload_to="works")),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Service name")),
                ("description", models.TextField(verbose_name="About Service")),
            ],
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "About Me", "verbose_name_plural": "About Me"},
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="about"
            ),
            preserve_default=False,
        ),
    ]
