# Generated by Django 4.2.3 on 2023-12-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_client_recentwork_service_alter_project_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="RecentWork",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
    ]
