# Generated by Django 4.2.3 on 2023-12-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
