# Generated by Django 4.2.3 on 2023-12-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(
                default="default_image.jpg", upload_to="static/images/"
            ),
        ),
    ]
