# Generated by Django 4.2.3 on 2023-12-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="feedback",
            field=models.TextField(default="Your default feedback here"),
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.TextField(default="Your default technologies here"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(default="default_image.jpg", upload_to="images/"),
        ),
    ]
