# Generated by Django 4.2.3 on 2023-12-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_project_feedback_project_technologies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
