# Generated by Django 4.2.3 on 2023-12-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_alter_project_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
    ]
