# Generated by Django 4.2.3 on 2023-12-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                default="default_image.png", upload_to="static/portfolio_images/"
            ),
        ),
    ]
