# Generated by Django 4.0.6 on 2026-04-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='project',
            name='feedback',
        ),
        migrations.AddField(
            model_name='project',
            name='clients',
            field=models.CharField(default='Enterprise clients globally', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(default='Developer', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='default_image.png', null=True, upload_to='static/portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
