# Generated by Django 4.2.3 on 2023-11-27 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                5, "Recipe must contain atleast 5 characters"
                            )
                        ],
                    ),
                ),
                ("rating", models.PositiveIntegerField()),
                ("detail", models.TextField(max_length=500)),
            ],
        ),
    ]
